### ISSUE TITLE
1-谭雅文-梅森数-pta

### ISSUE THREAD

**Issue by lizhiqi-creator** [permui/ZJUCKC-C-Learning-Assistence#3]
# 梅森数
## 形如2​n​​−1的素数称为梅森数（Mersenne Number）。例如2​2​​−1=3、2​3​​−1=7都是梅森数。1722年，双目失明的瑞士数学大师欧拉证明了2​31​​−1=2147483647是一个素数，堪称当时世界上“已知最大素数”的一个记录。

本题要求编写程序，对任一正整数n（n<20），输出所有不超过2​n​​−1的梅森数。

输入格式：

输入在一行中给出正整数n（n<20）。

输出格式：

按从小到大的顺序输出所有不超过2​n​​−1的梅森数，每行一个。如果完全没有，则输出“None”。
###
``` C
#include<stdio.h>
int main()
{
	int n,i,a,b,j;
		int isprime=1;
		int y=1;
	a=2;
	scanf("%d",&n);
	for(i=2;i<=n;i++)
	{
		a*=2;
		b=a-1;
		for(j=b-1;j>=2;j--)
		{
			if(b%j==0)
			{
				isprime=0;	
			}
			 
		}
		if (isprime==1)
![N~PQFZDG(AR78Q{CSJ)}7K6](https://user-images.githubusercontent.com/56906073/69413835-8c418080-0d4c-11ea-9aab-2de459f9e24c.png)

		{
		y=0;
		printf("%d\n",b);
		}
	}
	if(y==1)
	printf("None\n");
}
```
![N~PQFZDG(AR78Q{CSJ)}7K6](https://user-images.githubusercontent.com/56906073/69413973-c579f080-0d4c-11ea-89e2-e3c48b5eac55.png)

**Comment by sHut-0ff** [comment]
从你的代码来看，你应该还是比较懂这一题的，比如说isprime，y的使用。你对y的考虑是正确的，作为在范围内是否有结果的标志。但你对isprime可能少了一点考虑，你验证每一个形如2^n-1的数是否为质数，所以请你再考虑一下isprime=1这一句生命应该放在哪里？循环内还是循环外？
